-- Инициализация справочников

-- =====================================================
-- Описание: Заполнение справочника стран
-- =====================================================
INSERT INTO countries (name) VALUES
('Австралия'),
('Австрия'),
('Азербайджан'),
('Албания'),
('Алжир'),
('Ангола'),
('Андорра'),
('Антигуа и Барбуда'),
('Аргентина'),
('Армения'),
('Афганистан'),
('Багамы'),
('Бангладеш'),
('Барбадос'),
('Бахрейн'),
('Белиз'),
('Белоруссия'),
('Бельгия'),
('Бенин'),
('Болгария'),
('Боливия'),
('Босния и Герцеговина'),
('Ботсвана'),
('Бразилия'),
('Бруней'),
('Буркина-Фасо'),
('Бурунди'),
('Бутан'),
('Вануату'),
('Ватикан'),
('Великобритания'),
('Венгрия'),
('Венесуэла'),
('Восточный Тимор'),
('Вьетнам'),
('Габон'),
('Гаити'),
('Гайана'),
('Гамбия'),
('Гана'),
('Гватемала'),
('Гвинея'),
('Гвинея-Бисау'),
('Германия'),
('Гондурас'),
('Гренада'),
('Греция'),
('Грузия'),
('Дания'),
('Джибути'),
('Доминика'),
('Доминиканская Республика'),
('Египет'),
('Замбия'),
('Зимбабве'),
('Израиль'),
('Индия'),
('Индонезия'),
('Иордания'),
('Ирак'),
('Иран'),
('Ирландия'),
('Исландия'),
('Испания'),
('Италия'),
('Йемен'),
('Кабо-Верде'),
('Казахстан'),
('Камбоджа'),
('Камерун'),
('Канада'),
('Катар'),
('Кения'),
('Кипр'),
('Киргизия'),
('Кирибати'),
('Китай'),
('Колумбия'),
('Коморы'),
('Конго'),
('Коста-Рика'),
('Кот-д''Ивуар'),
('Куба'),
('Кувейт'),
('Лаос'),
('Латвия'),
('Лесото'),
('Либерия'),
('Ливан'),
('Ливия'),
('Литва'),
('Лихтенштейн'),
('Люксембург'),
('Маврикий'),
('Мавритания'),
('Мадагаскар'),
('Малави'),
('Малайзия'),
('Мали'),
('Мальдивы'),
('Мальта'),
('Марокко'),
('Маршалловы Острова'),
('Мексика'),
('Микронезия'),
('Мозамбик'),
('Молдавия'),
('Монако'),
('Монголия'),
('Мьянма'),
('Намибия'),
('Науру'),
('Непал'),
('Нигер'),
('Нигерия'),
('Нидерланды'),
('Никарагуа'),
('Новая Зеландия'),
('Норвегия'),
('Объединенные Арабские Эмираты'),
('Оман'),
('Пакистан'),
('Палау'),
('Панама'),
('Папуа-Новая Гвинея'),
('Парагвай'),
('Перу'),
('Польша'),
('Португалия'),
('Республика Корея'),
('Россия'),
('Руанда'),
('Румыния'),
('Сальвадор'),
('Самоа'),
('Сан-Марино'),
('Сан-Томе и Принсипи'),
('Саудовская Аравия'),
('Северная Корея'),
('Северная Македония'),
('Сейшелы'),
('Сенегал'),
('Сент-Винсент и Гренадины'),
('Сент-Китс и Невис'),
('Сент-Люсия'),
('Сербия'),
('Сингапур'),
('Сирия'),
('Словакия'),
('Словения'),
('Соломоновы Острова'),
('Сомали'),
('Судан'),
('Суринам'),
('США'),
('Сьерра-Леоне'),
('Таджикистан'),
('Таиланд'),
('Танзания'),
('Того'),
('Тонга'),
('Тринидад и Тобаго'),
('Тувалу'),
('Тунис'),
('Туркменистан'),
('Турция'),
('Уганда'),
('Узбекистан'),
('Украина'),
('Уругвай'),
('Фиджи'),
('Филиппины'),
('Финляндия'),
('Франция'),
('Хорватия'),
('Центральноафриканская Республика'),
('Чад'),
('Черногория'),
('Чехия'),
('Чили'),
('Швейцария'),
('Швеция'),
('Шри-Ланка'),
('Эквадор'),
('Экваториальная Гвинея'),
('Эритрея'),
('Эсватини'),
('Эстония'),
('Эфиопия'),
('ЮАР'),
('Южный Судан'),
('Ямайка'),
('Япония');


-- =====================================================
-- Описание: Заполнение справочника авторов
-- =====================================================

INSERT INTO authors (name, country_id) VALUES
-- Русские и советские авторы (Россия)
('Александр Пушкин', (SELECT id FROM countries WHERE name = 'Россия')),
('Лев Толстой', (SELECT id FROM countries WHERE name = 'Россия')),
('Федор Достоевский', (SELECT id FROM countries WHERE name = 'Россия')),
('Антон Чехов', (SELECT id FROM countries WHERE name = 'Россия')),
('Николай Гоголь', (SELECT id FROM countries WHERE name = 'Россия')),
('Михаил Булгаков', (SELECT id FROM countries WHERE name = 'Россия')),
('Иван Тургенев', (SELECT id FROM countries WHERE name = 'Россия')),
('Александр Солженицын', (SELECT id FROM countries WHERE name = 'Россия')),
('Борис Пастернак', (SELECT id FROM countries WHERE name = 'Россия')),
('Владимир Набоков', (SELECT id FROM countries WHERE name = 'Россия')),
('Михаил Шолохов', (SELECT id FROM countries WHERE name = 'Россия')),
('Александр Грибоедов', (SELECT id FROM countries WHERE name = 'Россия')),
('Иван Крылов', (SELECT id FROM countries WHERE name = 'Россия')),
('Николай Некрасов', (SELECT id FROM countries WHERE name = 'Россия')),
('Михаил Лермонтов', (SELECT id FROM countries WHERE name = 'Россия')),
('Андрей Сахаров', (SELECT id FROM countries WHERE name = 'Россия')),
('Алексей Толстой', (SELECT id FROM countries WHERE name = 'Россия')),
('Максим Горький', (SELECT id FROM countries WHERE name = 'Россия')),
('Владимир Маяковский', (SELECT id FROM countries WHERE name = 'Россия')),
('Сергей Есенин', (SELECT id FROM countries WHERE name = 'Россия')),
('Иосиф Бродский', (SELECT id FROM countries WHERE name = 'Россия')),
('Анна Ахматова', (SELECT id FROM countries WHERE name = 'Россия')),
('Марина Цветаева', (SELECT id FROM countries WHERE name = 'Россия')),
('Борис Акунин', (SELECT id FROM countries WHERE name = 'Россия')),
('Виктор Пелевин', (SELECT id FROM countries WHERE name = 'Россия')),
('Татьяна Толстая', (SELECT id FROM countries WHERE name = 'Россия')),
('Дмитрий Глуховский', (SELECT id FROM countries WHERE name = 'Россия')),
('Евгений Евтушенко', (SELECT id FROM countries WHERE name = 'Россия')),
('Константин Паустовский', (SELECT id FROM countries WHERE name = 'Россия')),
('Михаил Зощенко', (SELECT id FROM countries WHERE name = 'Россия')),

-- Авторы компьютерной литературы (Россия)
('Александр Шевченко', (SELECT id FROM countries WHERE name = 'Россия')),
('Виктор Гольцман', (SELECT id FROM countries WHERE name = 'Россия')),
('Евгений Зуев', (SELECT id FROM countries WHERE name = 'Россия')),
('Иван Голубев', (SELECT id FROM countries WHERE name = 'Россия')),
('Михаил Фленов', (SELECT id FROM countries WHERE name = 'Россия')),
('Павел Войта', (SELECT id FROM countries WHERE name = 'Россия')),
('Сергей Балакирев', (SELECT id FROM countries WHERE name = 'Россия')),
('Дмитрий Котеров', (SELECT id FROM countries WHERE name = 'Россия')),
('Алексей Балакирев', (SELECT id FROM countries WHERE name = 'Россия')),
('Вадим Пискунов', (SELECT id FROM countries WHERE name = 'Россия')),
('Алексей Хабибулин', (SELECT id FROM countries WHERE name = 'Россия')),
('Николай Комлев', (SELECT id FROM countries WHERE name = 'Россия')),
('Игорь Симдянов', (SELECT id FROM countries WHERE name = 'Россия')),
('Дмитрий Шевченко', (SELECT id FROM countries WHERE name = 'Россия')),
('Сергей Макаров', (SELECT id FROM countries WHERE name = 'Россия')),
('Андрей Пахомов', (SELECT id FROM countries WHERE name = 'Россия')),
('Денис Колисниченко', (SELECT id FROM countries WHERE name = 'Россия')),
('Елена Черткова', (SELECT id FROM countries WHERE name = 'Россия')),
('Александр Фролов', (SELECT id FROM countries WHERE name = 'Россия')),
('Григорий Шпарбер', (SELECT id FROM countries WHERE name = 'Россия')),

-- Зарубежные авторы компьютерной литературы (США)
('Эндрю Таненбаум', (SELECT id FROM countries WHERE name = 'США')),
('Брайан Керниган', (SELECT id FROM countries WHERE name = 'США')),
('Деннис Ритчи', (SELECT id FROM countries WHERE name = 'США')),
('Бьёрн Страуструп', (SELECT id FROM countries WHERE name = 'США')),
('Джеймс Гослинг', (SELECT id FROM countries WHERE name = 'США')),
('Гради Буч', (SELECT id FROM countries WHERE name = 'США')),
('Айвар Якобсон', (SELECT id FROM countries WHERE name = 'США')),
('Мартин Фаулер', (SELECT id FROM countries WHERE name = 'США')),
('Джошуа Блох', (SELECT id FROM countries WHERE name = 'США')),
('Роберт Мартин', (SELECT id FROM countries WHERE name = 'США')),
('Кент Бек', (SELECT id FROM countries WHERE name = 'США')),
('Уорд Каннингем', (SELECT id FROM countries WHERE name = 'США')),
('Эрик Гамма', (SELECT id FROM countries WHERE name = 'США')),
('Ричард Хелм', (SELECT id FROM countries WHERE name = 'США')),
('Ральф Джонсон', (SELECT id FROM countries WHERE name = 'США')),
('Джон Влиссидес', (SELECT id FROM countries WHERE name = 'США')),
('Герберт Шилдт', (SELECT id FROM countries WHERE name = 'США')),
('Стивен Прата', (SELECT id FROM countries WHERE name = 'США')),
('Дейв Томас', (SELECT id FROM countries WHERE name = 'США')),
('Брюс Эккель', (SELECT id FROM countries WHERE name = 'США')),
('Ричард Стивенс', (SELECT id FROM countries WHERE name = 'США')),
('Стив Макконнелл', (SELECT id FROM countries WHERE name = 'США')),
('Тим О''Рейли', (SELECT id FROM countries WHERE name = 'США')),
('Пол Грэм', (SELECT id FROM countries WHERE name = 'США')),
('Джоэл Спольски', (SELECT id FROM countries WHERE name = 'США')),
('Джефф Этвуд', (SELECT id FROM countries WHERE name = 'США')),
('Джон Кармак', (SELECT id FROM countries WHERE name = 'США')),
('Майкл Абраш', (SELECT id FROM countries WHERE name = 'США')),
('Дональд Кнут', (SELECT id FROM countries WHERE name = 'США')),
('Томас Кормен', (SELECT id FROM countries WHERE name = 'США')),
('Чарльз Лейзерсон', (SELECT id FROM countries WHERE name = 'США')),
('Рональд Ривест', (SELECT id FROM countries WHERE name = 'США')),
('Клиффорд Штайн', (SELECT id FROM countries WHERE name = 'США')),
('Аллен Доул', (SELECT id FROM countries WHERE name = 'США')),
('Эндрю Хант', (SELECT id FROM countries WHERE name = 'США')),
('Джон Скит', (SELECT id FROM countries WHERE name = 'США')),
('Билл Вагнер', (SELECT id FROM countries WHERE name = 'США')),
('Скотт Майерс', (SELECT id FROM countries WHERE name = 'США')),
('Стивен Мейерс', (SELECT id FROM countries WHERE name = 'США')),
('Марк Саммерфильд', (SELECT id FROM countries WHERE name = 'США')),
('Крейг Уоллс', (SELECT id FROM countries WHERE name = 'США')),
('Джастин Секулес', (SELECT id FROM countries WHERE name = 'США')),
('Майкл Хартл', (SELECT id FROM countries WHERE name = 'США')),
('Стефан Эйб', (SELECT id FROM countries WHERE name = 'США')),
('Антонио Гонсалвес', (SELECT id FROM countries WHERE name = 'США')),
('Роберт Седжвик', (SELECT id FROM countries WHERE name = 'США')),
('Кевин Уэйн', (SELECT id FROM countries WHERE name = 'США')),
('Гэри Брэдски', (SELECT id FROM countries WHERE name = 'США')),
('Бен Фрай', (SELECT id FROM countries WHERE name = 'США')),
('Том ДеМарко', (SELECT id FROM countries WHERE name = 'США')),
('Тимоти Листер', (SELECT id FROM countries WHERE name = 'США')),

-- Зарубежные авторы компьютерной литературы (Англия)
('Алан Тьюринг', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Тим Бернерс-Ли', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Рей', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Саймон Браун', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Крис Чепмен', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Иэн Соммервилл', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Хаттон', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Крис Солтер', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Дакетт', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Дэвид Флэнаган', (SELECT id FROM countries WHERE name = 'Великобритания')),

-- Зарубежные авторы компьютерной литературы (Германия)
('Бертран Мейер', (SELECT id FROM countries WHERE name = 'Германия')),
('Франц Бауман', (SELECT id FROM countries WHERE name = 'Германия')),
('Петер Линден', (SELECT id FROM countries WHERE name = 'Германия')),
('Клаус Билецки', (SELECT id FROM countries WHERE name = 'Германия')),
('Томас Беккер', (SELECT id FROM countries WHERE name = 'Германия')),

-- Зарубежные авторы компьютерной литературы (Нидерланды)
('Гвидо ван Россум', (SELECT id FROM countries WHERE name = 'Нидерланды')),
('Эдсгер Дейкстра', (SELECT id FROM countries WHERE name = 'Нидерланды')),

-- Зарубежные авторы компьютерной литературы (Канада)
('Джеймс Гошен', (SELECT id FROM countries WHERE name = 'Канада')),
('Майкл Эллис', (SELECT id FROM countries WHERE name = 'Канада')),
('Брюс Френсис', (SELECT id FROM countries WHERE name = 'Канада')),

-- Зарубежные авторы компьютерной литературы (Япония)
('Юкихиро Мацумото', (SELECT id FROM countries WHERE name = 'Япония')),
('Кендзи Хирано', (SELECT id FROM countries WHERE name = 'Япония')),
('Хисао Такахаси', (SELECT id FROM countries WHERE name = 'Япония')),

-- Зарубежные авторы компьютерной литературы (Дания)
('Андерс Хейлсберг', (SELECT id FROM countries WHERE name = 'Дания')),

-- Зарубежные авторы компьютерной литературы (Финляндия)
('Линус Торвальдс', (SELECT id FROM countries WHERE name = 'Финляндия')),

-- Классическая литература - США
('Марк Твен', (SELECT id FROM countries WHERE name = 'США')),
('Эрнест Хемингуэй', (SELECT id FROM countries WHERE name = 'США')),
('Фрэнсис Скотт Фицджеральд', (SELECT id FROM countries WHERE name = 'США')),
('Уильям Фолкнер', (SELECT id FROM countries WHERE name = 'США')),
('Джон Стейнбек', (SELECT id FROM countries WHERE name = 'США')),
('Эдгар Аллан По', (SELECT id FROM countries WHERE name = 'США')),
('Герман Мелвилл', (SELECT id FROM countries WHERE name = 'США')),
('Натаниэль Готорн', (SELECT id FROM countries WHERE name = 'США')),
('Генри Джеймс', (SELECT id FROM countries WHERE name = 'США')),
('Теодор Драйзер', (SELECT id FROM countries WHERE name = 'США')),
('Синклер Льюис', (SELECT id FROM countries WHERE name = 'США')),
('Рэй Брэдбери', (SELECT id FROM countries WHERE name = 'США')),
('Айзек Азимов', (SELECT id FROM countries WHERE name = 'США')),
('Роберт Хайнлайн', (SELECT id FROM countries WHERE name = 'США')),
('Курт Воннегут', (SELECT id FROM countries WHERE name = 'США')),
('Артур Миллер', (SELECT id FROM countries WHERE name = 'США')),
('Теннесси Уильямс', (SELECT id FROM countries WHERE name = 'США')),
('Харпер Ли', (SELECT id FROM countries WHERE name = 'США')),
('Джером Сэлинджер', (SELECT id FROM countries WHERE name = 'США')),
('Тони Моррисон', (SELECT id FROM countries WHERE name = 'США')),
('Джек Лондон', (SELECT id FROM countries WHERE name = 'США')),
('Джон Эпдайк', (SELECT id FROM countries WHERE name = 'США')),
('Норман Мейлер', (SELECT id FROM countries WHERE name = 'США')),
('Уолт Уитмен', (SELECT id FROM countries WHERE name = 'США')),
('Эмили Дикинсон', (SELECT id FROM countries WHERE name = 'США')),
('Роберт Фрост', (SELECT id FROM countries WHERE name = 'США')),

-- Классическая литература - Великобритания
('Уильям Шекспир', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Чарльз Диккенс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джейн Остин', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Шарлотта Бронте', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Эмили Бронте', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джордж Оруэлл', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Олдос Хаксли', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Рональд Руэл Толкин', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Клайв Стейплз Льюис', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Артур Конан Дойль', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Агата Кристи', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Герберт Уэллс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джонатан Свифт', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Дэниел Дефо', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Сомерсет Моэм', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Грэм Грин', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Ивлин Во', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джеймс Джойс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Вирджиния Вулф', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Эдвард Форстер', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Уильям Блейк', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Мильтон', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джефри Чосер', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Александр Поуп', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Перси Биши Шелли', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джон Китс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Альфред Теннисон', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Редьярд Киплинг', (SELECT id FROM countries WHERE name = 'Великобритания')),

-- Классическая литература - Франция
('Виктор Гюго', (SELECT id FROM countries WHERE name = 'Франция')),
('Оноре де Бальзак', (SELECT id FROM countries WHERE name = 'Франция')),
('Гюстав Флобер', (SELECT id FROM countries WHERE name = 'Франция')),
('Эмиль Золя', (SELECT id FROM countries WHERE name = 'Франция')),
('Марсель Пруст', (SELECT id FROM countries WHERE name = 'Франция')),
('Александр Дюма', (SELECT id FROM countries WHERE name = 'Франция')),
('Жюль Верн', (SELECT id FROM countries WHERE name = 'Франция')),
('Мольер', (SELECT id FROM countries WHERE name = 'Франция')),
('Жан-Батист Расин', (SELECT id FROM countries WHERE name = 'Франция')),
('Пьер Корнель', (SELECT id FROM countries WHERE name = 'Франция')),
('Вольтер', (SELECT id FROM countries WHERE name = 'Франция')),
('Жан-Жак Руссо', (SELECT id FROM countries WHERE name = 'Франция')),
('Шарль Бодлер', (SELECT id FROM countries WHERE name = 'Франция')),
('Артюр Рембо', (SELECT id FROM countries WHERE name = 'Франция')),
('Стендаль', (SELECT id FROM countries WHERE name = 'Франция')),
('Андре Жид', (SELECT id FROM countries WHERE name = 'Франция')),
('Франсуа Рабле', (SELECT id FROM countries WHERE name = 'Франция')),
('Альбер Камю', (SELECT id FROM countries WHERE name = 'Франция')),

-- Классическая литература - Германия
('Иоганн Вольфганг Гёте', (SELECT id FROM countries WHERE name = 'Германия')),
('Фридрих Шиллер', (SELECT id FROM countries WHERE name = 'Германия')),
('Генрих Гейне', (SELECT id FROM countries WHERE name = 'Германия')),
('Томас Манн', (SELECT id FROM countries WHERE name = 'Германия')),
('Герман Гессе', (SELECT id FROM countries WHERE name = 'Германия')),
('Франц Кафка', (SELECT id FROM countries WHERE name = 'Германия')),
('Бертольд Брехт', (SELECT id FROM countries WHERE name = 'Германия')),
('Гюнтер Грасс', (SELECT id FROM countries WHERE name = 'Германия')),

-- Классическая литература - Италия
('Данте Алигьери', (SELECT id FROM countries WHERE name = 'Италия')),
('Франческо Петрарка', (SELECT id FROM countries WHERE name = 'Италия')),
('Джованни Боккаччо', (SELECT id FROM countries WHERE name = 'Италия')),
('Никколо Макиавелли', (SELECT id FROM countries WHERE name = 'Италия')),
('Алессандро Мандзони', (SELECT id FROM countries WHERE name = 'Италия')),
('Итало Кальвино', (SELECT id FROM countries WHERE name = 'Италия')),
('Умберто Эко', (SELECT id FROM countries WHERE name = 'Италия')),

-- Классическая литература - Испания
('Мигель де Сервантес', (SELECT id FROM countries WHERE name = 'Испания')),
('Лопе де Вега', (SELECT id FROM countries WHERE name = 'Испания')),
('Педро Кальдерон', (SELECT id FROM countries WHERE name = 'Испания')),
('Федерико Гарсиа Лорка', (SELECT id FROM countries WHERE name = 'Испания')),
('Габриэль Гарсиа Маркес', (SELECT id FROM countries WHERE name = 'Колумбия')),

-- Классическая литература - Норвегия
('Генрик Ибсен', (SELECT id FROM countries WHERE name = 'Норвегия')),
('Кнут Гамсун', (SELECT id FROM countries WHERE name = 'Норвегия')),

-- Классическая литература - Швеция
('Астрид Линдгрен', (SELECT id FROM countries WHERE name = 'Швеция')),
('Сельма Лагерлёф', (SELECT id FROM countries WHERE name = 'Швеция')),

-- Классическая литература - Греция
('Гомер', (SELECT id FROM countries WHERE name = 'Греция')),
('Софокл', (SELECT id FROM countries WHERE name = 'Греция')),
('Еврипид', (SELECT id FROM countries WHERE name = 'Греция')),
('Аристофан', (SELECT id FROM countries WHERE name = 'Греция')),

-- Современная зарубежная литература
('Харуки Мураками', (SELECT id FROM countries WHERE name = 'Япония')),
('Кадзуо Исигуро', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Салман Рушди', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Амитав Гош', (SELECT id FROM countries WHERE name = 'Индия')),
('Чимаманда Нгози Адичи', (SELECT id FROM countries WHERE name = 'Нигерия')),
('Джон Грин', (SELECT id FROM countries WHERE name = 'США')),
('Стивен Кинг', (SELECT id FROM countries WHERE name = 'США')),
('Дэн Браун', (SELECT id FROM countries WHERE name = 'США')),
('Джордж Мартин', (SELECT id FROM countries WHERE name = 'США')),
('Патрик Ротфусс', (SELECT id FROM countries WHERE name = 'США')),
('Нил Гейман', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Терри Пратчетт', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Дуглас Адамс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Янн Мартель', (SELECT id FROM countries WHERE name = 'Канада')),
('Маргарет Этвуд', (SELECT id FROM countries WHERE name = 'Канада')),
('Алис Манро', (SELECT id FROM countries WHERE name = 'Канада')),
('Элиф Шафак', (SELECT id FROM countries WHERE name = 'Турция')),
('Орхан Памук', (SELECT id FROM countries WHERE name = 'Турция')),
('Хорхе Луис Борхес', (SELECT id FROM countries WHERE name = 'Аргентина')),
('Пабло Неруда', (SELECT id FROM countries WHERE name = 'Чили')),
('Исабель Альенде', (SELECT id FROM countries WHERE name = 'Чили')),
('Марио Варгас Льоса', (SELECT id FROM countries WHERE name = 'Перу')),
('Карлос Фуэнтес', (SELECT id FROM countries WHERE name = 'Мексика')),
('Октавио Пас', (SELECT id FROM countries WHERE name = 'Мексика')),
('Джон Фаулз', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Мюриэл Спарк', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Дорис Лессинг', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Видиадхар Найпол', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Надин Гордимер', (SELECT id FROM countries WHERE name = 'ЮАР')),
('Джонатан Коу', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Иэн Макьюэн', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джулиан Барнс', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Мартин Эмис', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Уильям Голдинг', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Томас Харди', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Джозеф Конрад', (SELECT id FROM countries WHERE name = 'Великобритания')),

-- Дополнительные современные авторы (США)
('Донна Тартт', (SELECT id FROM countries WHERE name = 'США')),
('Джонатан Франзен', (SELECT id FROM countries WHERE name = 'США')),
('Джеффри Евгенидис', (SELECT id FROM countries WHERE name = 'США')),
('Дженнифер Иган', (SELECT id FROM countries WHERE name = 'США')),
('Денис Джонсон', (SELECT id FROM countries WHERE name = 'США')),
('Кормак Маккарти', (SELECT id FROM countries WHERE name = 'США')),
('Филип Рот', (SELECT id FROM countries WHERE name = 'США')),
('Пол Остер', (SELECT id FROM countries WHERE name = 'США')),
('Стивен Кинг', (SELECT id FROM countries WHERE name = 'США')),
('Дианна Уинн Джонс', (SELECT id FROM countries WHERE name = 'США')),
('Урсула Ле Гуин', (SELECT id FROM countries WHERE name = 'США')),
('Филип Дик', (SELECT id FROM countries WHERE name = 'США')),
('Роджер Желязны', (SELECT id FROM countries WHERE name = 'США')),
('Гарри Гаррисон', (SELECT id FROM countries WHERE name = 'США')),
('Клиффорд Саймак', (SELECT id FROM countries WHERE name = 'США')),

-- Украинские авторы
('Тарас Шевченко', (SELECT id FROM countries WHERE name = 'Украина')),
('Иван Франко', (SELECT id FROM countries WHERE name = 'Украина')),
('Леся Украинка', (SELECT id FROM countries WHERE name = 'Украина')),
('Михаил Коцюбинский', (SELECT id FROM countries WHERE name = 'Украина')),
('Иван Нечуй-Левицкий', (SELECT id FROM countries WHERE name = 'Украина')),
('Панас Мирный', (SELECT id FROM countries WHERE name = 'Украина')),
('Марко Вовчок', (SELECT id FROM countries WHERE name = 'Украина')),
('Григорий Сковорода', (SELECT id FROM countries WHERE name = 'Украина')),
('Лина Костенко', (SELECT id FROM countries WHERE name = 'Украина')),
('Оксана Забужко', (SELECT id FROM countries WHERE name = 'Украина')),
('Сергей Жадан', (SELECT id FROM countries WHERE name = 'Украина')),
('Юрий Андрухович', (SELECT id FROM countries WHERE name = 'Украина')),
('Андрей Курков', (SELECT id FROM countries WHERE name = 'Украина')),

-- Авторы компьютерной литературы - дополнительно (Индия)
('Алок Кумар', (SELECT id FROM countries WHERE name = 'Индия')),
('Пратап Мурти', (SELECT id FROM countries WHERE name = 'Индия')),
('Суджата Рао', (SELECT id FROM countries WHERE name = 'Индия')),

-- Авторы компьютерной литературы - Китай
('Ли Фэн', (SELECT id FROM countries WHERE name = 'Китай')),
('Ван Цзянь', (SELECT id FROM countries WHERE name = 'Китай')),
('Чжан Вэй', (SELECT id FROM countries WHERE name = 'Китай')),

-- Авторы компьютерной литературы - Израиль
('Элияху Голдратт', (SELECT id FROM countries WHERE name = 'Израиль')),
('Дорон Друкер', (SELECT id FROM countries WHERE name = 'Израиль')),

-- Писатели-фантасты (дополнительно)
('Братья Стругацкие', (SELECT id FROM countries WHERE name = 'Россия')),
('Александр Беляев', (SELECT id FROM countries WHERE name = 'Россия')),
('Иван Ефремов', (SELECT id FROM countries WHERE name = 'Россия')),
('Кир Булычев', (SELECT id FROM countries WHERE name = 'Россия')),
('Евгений Замятин', (SELECT id FROM countries WHERE name = 'Россия')),
('Андрей Платонов', (SELECT id FROM countries WHERE name = 'Россия')),
('Сергей Лукьяненко', (SELECT id FROM countries WHERE name = 'Россия')),
('Ник Перумов', (SELECT id FROM countries WHERE name = 'Россия')),
('Вадим Панов', (SELECT id FROM countries WHERE name = 'Россия')),
('Дмитрий Глуховский', (SELECT id FROM countries WHERE name = 'Россия')),
('Алексей Иванов', (SELECT id FROM countries WHERE name = 'Россия')),
('Захар Прилепин', (SELECT id FROM countries WHERE name = 'Россия')),
('Евгений Водолазкин', (SELECT id FROM countries WHERE name = 'Россия')),
('Гузель Яхина', (SELECT id FROM countries WHERE name = 'Россия')),
('Сергей Довлатов', (SELECT id FROM countries WHERE name = 'Россия')),
('Василий Шукшин', (SELECT id FROM countries WHERE name = 'Россия')),
('Андрей Битов', (SELECT id FROM countries WHERE name = 'Россия')),
('Георгий Владимов', (SELECT id FROM countries WHERE name = 'Россия')),
('Борис Шергин', (SELECT id FROM countries WHERE name = 'Россия')),
('Фазиль Искандер', (SELECT id FROM countries WHERE name = 'Россия')),
('Даниил Гранин', (SELECT id FROM countries WHERE name = 'Россия'));


-- =====================================================
-- Описание: Заполнение справочника издательств
-- =====================================================

INSERT INTO publishings (name, description, country_id) VALUES
-- Российские издательства (компьютерная литература)
('Питер', 'Одно из ведущих издательств компьютерной и деловой литературы в России', (SELECT id FROM countries WHERE name = 'Россия')),
('Диалектика', 'Специализируется на переводной компьютерной литературе', (SELECT id FROM countries WHERE name = 'Россия')),
('БХВ-Петербург', 'Издает техническую литературу, программирование, радиотехнику', (SELECT id FROM countries WHERE name = 'Россия')),
('Эксмо', 'Крупнейшее российское издательство, выпускает компьютерную литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('АСТ', 'Издает компьютерную литературу в серии "Компьютерная академия"', (SELECT id FROM countries WHERE name = 'Россия')),
('Манн, Иванов и Фербер', 'Современное издательство бизнес-литературы, в т.ч. IT-тематики', (SELECT id FROM countries WHERE name = 'Россия')),
('ООО "Литрес"', 'Крупнейший цифровой книжный сервис, издает электронные книги', (SELECT id FROM countries WHERE name = 'Россия')),
('КноРус', 'Издает учебную литературу по информационным технологиям', (SELECT id FROM countries WHERE name = 'Россия')),
('Юрайт', 'Издательство учебной литературы для вузов, включая IT', (SELECT id FROM countries WHERE name = 'Россия')),
('Синергия', 'Издает бизнес-литературу и IT-менеджмент', (SELECT id FROM countries WHERE name = 'Россия')),
('Интеллект-Центр', 'Издает компьютерную литературу и учебные пособия', (SELECT id FROM countries WHERE name = 'Россия')),
('Лаборатория знаний', 'Научно-техническая литература, включая ИТ', (SELECT id FROM countries WHERE name = 'Россия')),
('СОЛОН-Пресс', 'Издает литературу по программированию и электронике', (SELECT id FROM countries WHERE name = 'Россия')),
('ДМК Пресс', 'Издательство компьютерной литературы, включая серию "Для профессионалов"', (SELECT id FROM countries WHERE name = 'Россия')),
('Новый издательский дом', 'Издает учебную литературу, в т.ч. IT', (SELECT id FROM countries WHERE name = 'Россия')),
('Санкт-Петербургский университет', 'Университетское издательство, выпускает учебники по IT', (SELECT id FROM countries WHERE name = 'Россия')),

-- Российские издательства (художественная литература)
('Азбука-Аттикус', 'Издает русскую и зарубежную классику', (SELECT id FROM countries WHERE name = 'Россия')),
('Иностранка', 'Переводная зарубежная литература', (SELECT id FROM countries WHERE name = 'Россия')),
('КоЛибри', 'Интеллектуальная, нон-фикшн литература', (SELECT id FROM countries WHERE name = 'Россия')),
('Время', 'Художественная и научно-популярная литература', (SELECT id FROM countries WHERE name = 'Россия')),
('Захаров', 'Издательство русских и зарубежных авторов', (SELECT id FROM countries WHERE name = 'Россия')),
('ОГИ', 'Издает современную поэзию и прозу', (SELECT id FROM countries WHERE name = 'Россия')),
('НЛО', 'Новое литературное обозрение - научные издания', (SELECT id FROM countries WHERE name = 'Россия')),
('Рипол-Классик', 'Классическая литература, нон-фикшн', (SELECT id FROM countries WHERE name = 'Россия')),
('Ад Маргинем', 'Интеллектуальная литература, философия', (SELECT id FROM countries WHERE name = 'Россия')),
('Corpus', 'Издательская группа АСТ, художественная литература', (SELECT id FROM countries WHERE name = 'Россия')),

-- Зарубежные издательства компьютерной литературы (США)
('O''Reilly Media', 'Ведущее издательство технической литературы, известное своими книгами по программированию', (SELECT id FROM countries WHERE name = 'США')),
('Apress', 'Издает профессиональную литературу по программированию и разработке ПО', (SELECT id FROM countries WHERE name = 'США')),
('Manning Publications', 'Известно серией "In Action" по различным технологиям', (SELECT id FROM countries WHERE name = 'США')),
('Addison-Wesley', 'Классическое издательство компьютерной литературы (издательство Кернигана и Ритчи)', (SELECT id FROM countries WHERE name = 'США')),
('Prentice Hall', 'Издает литературу по программированию, системам, сетям', (SELECT id FROM countries WHERE name = 'США')),
('Wiley', 'Крупнейшее издательство, выпускает книги по IT для профессионалов', (SELECT id FROM countries WHERE name = 'США')),
('Morgan Kaufmann', 'Специализируется на издательстве книг по информатике и программированию', (SELECT id FROM countries WHERE name = 'США')),
('MIT Press', 'Издательство Массачусетского технологического института, научная литература', (SELECT id FROM countries WHERE name = 'США')),
('Packt Publishing', 'Издает современную литературу по веб-разработке, фреймворкам, DevOps', (SELECT id FROM countries WHERE name = 'США')),
('No Starch Press', 'Издает книги по программированию, хакерству, кибербезопасности', (SELECT id FROM countries WHERE name = 'США')),
('Sams Publishing', 'Известно серией книг "Teach Yourself" по различным технологиям', (SELECT id FROM countries WHERE name = 'США')),
('Sybex', 'Издает книги по IT-сертификации, сетям, программированию', (SELECT id FROM countries WHERE name = 'США')),
('For Dummies', 'Серия книг для начинающих, включая IT-тематику', (SELECT id FROM countries WHERE name = 'США')),
('Microsoft Press', 'Официальное издательство Microsoft, выпускает документацию и учебники', (SELECT id FROM countries WHERE name = 'США')),
('Pearson Education', 'Крупнейшее образовательное издательство, включает Addison-Wesley, Prentice Hall', (SELECT id FROM countries WHERE name = 'США')),
('Springer', 'Издательство научной литературы, включая информатику', (SELECT id FROM countries WHERE name = 'США')),
('Elsevier', 'Крупнейшее издательство научной и медицинской литературы, включая информатику', (SELECT id FROM countries WHERE name = 'США')),

-- Зарубежные издательства компьютерной литературы (Великобритания)
('Cambridge University Press', 'Издает научную литературу, включая информатику', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Oxford University Press', 'Крупнейшее университетское издательство, учебная литература', (SELECT id FROM countries WHERE name = 'Великобритания')),
('BPB Publications', 'Издает компьютерную литературу и учебники по IT', (SELECT id FROM countries WHERE name = 'Великобритания')),
('McGraw-Hill', 'Крупнейшее издательство, выпускает техническую литературу', (SELECT id FROM countries WHERE name = 'Великобритания')),

-- Зарубежные издательства компьютерной литературы (Германия)
('Springer-Verlag', 'Издательство научной литературы, включая информатику', (SELECT id FROM countries WHERE name = 'Германия')),
('dpunkt.verlag', 'Немецкое издательство компьютерной литературы', (SELECT id FROM countries WHERE name = 'Германия')),
('Rheinwerk Verlag', 'Издает книги по программированию и информатике на немецком языке', (SELECT id FROM countries WHERE name = 'Германия')),
('MIT Press', 'Издательство MIT Press, включая немецкий филиал', (SELECT id FROM countries WHERE name = 'Германия')),

-- Зарубежные издательства компьютерной литературы (Япония)
('O''Reilly Japan', 'Японский филиал O''Reilly Media', (SELECT id FROM countries WHERE name = 'Япония')),
('Kodansha', 'Крупнейшее японское издательство, выпускает компьютерную литературу', (SELECT id FROM countries WHERE name = 'Япония')),
('Shueisha', 'Издает мангу, но также IT-литературу', (SELECT id FROM countries WHERE name = 'Япония')),
('Gijutsu-Hyoronsha', 'Издает техническую и компьютерную литературу', (SELECT id FROM countries WHERE name = 'Япония')),

-- Зарубежные издательства компьютерной литературы (Индия)
('Tata McGraw-Hill', 'Индийское издательство учебной и технической литературы', (SELECT id FROM countries WHERE name = 'Индия')),
('BPB Publications', 'Крупнейшее индийское издательство IT-литературы', (SELECT id FROM countries WHERE name = 'Индия')),
('Dreamtech Press', 'Издает компьютерную литературу и учебники', (SELECT id FROM countries WHERE name = 'Индия')),
('Prentice Hall India', 'Индийский филиал Prentice Hall', (SELECT id FROM countries WHERE name = 'Индия')),
('S. Chand Publishing', 'Старейшее индийское издательство учебной литературы', (SELECT id FROM countries WHERE name = 'Индия')),

-- Зарубежные издательства компьютерной литературы (Китай)
('Tsinghua University Press', 'Издательство Университета Цинхуа, выпускает компьютерную литературу', (SELECT id FROM countries WHERE name = 'Китай')),
('China Machine Press', 'Крупнейшее китайское издательство технической литературы', (SELECT id FROM countries WHERE name = 'Китай')),
('Publishing House of Electronics Industry', 'Издает книги по электронике и компьютерным наукам', (SELECT id FROM countries WHERE name = 'Китай')),
('People''s Posts and Telecommunications Press', 'Издает литературу по телекоммуникациям и IT', (SELECT id FROM countries WHERE name = 'Китай')),

-- Зарубежные издательства компьютерной литературы (Франция)
('Eyrolles', 'Французское издательство, выпускает компьютерную литературу', (SELECT id FROM countries WHERE name = 'Франция')),
('Dunod', 'Издает научную и техническую литературу', (SELECT id FROM countries WHERE name = 'Франция')),
('O''Reilly France', 'Французский филиал O''Reilly Media', (SELECT id FROM countries WHERE name = 'Франция')),
('Lavoisier', 'Издает техническую литературу и IT', (SELECT id FROM countries WHERE name = 'Франция')),

-- Зарубежные издательства компьютерной литературы (Италия)
('Hoepli', 'Старейшее итальянское издательство, выпускает компьютерную литературу', (SELECT id FROM countries WHERE name = 'Италия')),
('McGraw-Hill Italia', 'Итальянский филиал McGraw-Hill', (SELECT id FROM countries WHERE name = 'Италия')),
('Apogeo', 'Специализируется на компьютерной литературе', (SELECT id FROM countries WHERE name = 'Италия')),

-- Зарубежные издательства компьютерной литературы (Испания)
('Anaya Multimedia', 'Испанское издательство компьютерной литературы', (SELECT id FROM countries WHERE name = 'Испания')),
('McGraw-Hill Interamericana', 'Испанский филиал McGraw-Hill', (SELECT id FROM countries WHERE name = 'Испания')),
('Ra-Ma', 'Издает компьютерную литературу и учебники', (SELECT id FROM countries WHERE name = 'Испания')),

-- Зарубежные издательства компьютерной литературы (Нидерланды)
('Elsevier Science', 'Издает научную литературу, включая информатику', (SELECT id FROM countries WHERE name = 'Нидерланды')),
('Springer Netherlands', 'Нидерландский филиал Springer', (SELECT id FROM countries WHERE name = 'Нидерланды')),

-- Зарубежные издательства компьютерной литературы (Австралия)
('Cengage Learning', 'Австралийский филиал, издает учебную литературу', (SELECT id FROM countries WHERE name = 'Австралия')),
('Wiley Australia', 'Австралийский филиал Wiley', (SELECT id FROM countries WHERE name = 'Австралия')),

-- Зарубежные издательства компьютерной литературы (Канада)
('McGraw-Hill Ryerson', 'Канадский филиал McGraw-Hill', (SELECT id FROM countries WHERE name = 'Канада')),
('Nelson Education', 'Канадское издательство учебной литературы', (SELECT id FROM countries WHERE name = 'Канада')),

-- Зарубежные издательства компьютерной литературы (Израиль)
('Jerusalem Academic Press', 'Издает академическую литературу, включая IT', (SELECT id FROM countries WHERE name = 'Израиль')),

-- Зарубежные издательства компьютерной литературы (Южная Корея)
('Seoul National University Press', 'Издательство Сеульского национального университета', (SELECT id FROM countries WHERE name = 'Республика Корея')),
('Bookshill', 'Корейское издательство компьютерной литературы', (SELECT id FROM countries WHERE name = 'Республика Корея')),

-- Зарубежные издательства компьютерной литературы (Бразилия)
('Novatec Editora', 'Бразильское издательство компьютерной литературы', (SELECT id FROM countries WHERE name = 'Бразилия')),
('Pearson Brasil', 'Бразильский филиал Pearson', (SELECT id FROM countries WHERE name = 'Бразилия')),
('Editora Campus', 'Издает техническую литературу в Бразилии', (SELECT id FROM countries WHERE name = 'Бразилия')),

-- Зарубежные издательства компьютерной литературы (Мексика)
('McGraw-Hill Mexico', 'Мексиканский филиал McGraw-Hill', (SELECT id FROM countries WHERE name = 'Мексика')),
('Alfaomega', 'Издает компьютерную литературу и учебники', (SELECT id FROM countries WHERE name = 'Мексика')),

-- Украинские издательства
('Видавництво Старого Лева', 'Издает художественную и детскую литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Фоліо', 'Одно из крупнейших издательств Украины, художественная литература', (SELECT id FROM countries WHERE name = 'Украина')),
('А-БА-БА-ГА-ЛА-МА-ГА', 'Издает детскую литературу и классику', (SELECT id FROM countries WHERE name = 'Украина')),
('Клуб Сімейного Дозвілля', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Віхола', 'Издает современную художественную литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Комора', 'Издает современную украинскую литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Український письменник', 'Издает украинскую классику и современную литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Смолоскип', 'Издает украинскую поэзию и прозу', (SELECT id FROM countries WHERE name = 'Украина')),
('Критика', 'Издает интеллектуальную и научную литературу', (SELECT id FROM countries WHERE name = 'Украина')),
('Дух і Літера', 'Издает гуманитарную литературу', (SELECT id FROM countries WHERE name = 'Украина')),

-- Классические литературные издательства (США)
('Penguin Random House', 'Крупнейшее издательство в мире, художественная литература', (SELECT id FROM countries WHERE name = 'США')),
('HarperCollins', 'Издает художественную литературу и нон-фикшн', (SELECT id FROM countries WHERE name = 'США')),
('Simon & Schuster', 'Классическое американское издательство', (SELECT id FROM countries WHERE name = 'США')),
('Hachette Book Group', 'Издает художественную и научную литературу', (SELECT id FROM countries WHERE name = 'США')),
('Macmillan Publishers', 'Издает художественную литературу и учебники', (SELECT id FROM countries WHERE name = 'США')),
('Scholastic Corporation', 'Издает детскую литературу, образовательные материалы', (SELECT id FROM countries WHERE name = 'США')),
('Houghton Mifflin Harcourt', 'Издает художественную и учебную литературу', (SELECT id FROM countries WHERE name = 'США')),
('John Wiley & Sons', 'Издает научную и профессиональную литературу', (SELECT id FROM countries WHERE name = 'США')),
('Chronicle Books', 'Издает иллюстрированные книги, нон-фикшн', (SELECT id FROM countries WHERE name = 'США')),

-- Классические литературные издательства (Великобритания)
('Penguin Books', 'Легендарное британское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Faber and Faber', 'Издает поэзию, драматургию, художественную литературу', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Bloomsbury Publishing', 'Известно изданием серии книг о Гарри Поттере', (SELECT id FROM countries WHERE name = 'Великобритания')),
('HarperCollins UK', 'Британский филиал HarperCollins', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Orion Publishing Group', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Allen & Unwin', 'Австралийско-британское издательство', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Vintage Books', 'Издает современную художественную литературу', (SELECT id FROM countries WHERE name = 'Великобритания')),
('Canongate Books', 'Шотландское издательство, художественная литература', (SELECT id FROM countries WHERE name = 'Великобритания')),

-- Классические литературные издательства (Франция)
('Gallimard', 'Крупнейшее французское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Франция')),
('Éditions du Seuil', 'Издает художественную и гуманитарную литературу', (SELECT id FROM countries WHERE name = 'Франция')),
('Hachette Livre', 'Крупнейшее французское издательство', (SELECT id FROM countries WHERE name = 'Франция')),
('Éditions Flammarion', 'Издает художественную литературу и искусство', (SELECT id FROM countries WHERE name = 'Франция')),
('Éditions Albin Michel', 'Издает художественную и религиозную литературу', (SELECT id FROM countries WHERE name = 'Франция')),
('Éditions Robert Laffont', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Франция')),

-- Классические литературные издательства (Германия)
('S. Fischer Verlag', 'Немецкое издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Германия')),
('Suhrkamp Verlag', 'Известное немецкое издательство гуманитарной литературы', (SELECT id FROM countries WHERE name = 'Германия')),
('Rowohlt Verlag', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Германия')),
('Carl Hanser Verlag', 'Издает художественную и научную литературу', (SELECT id FROM countries WHERE name = 'Германия')),

-- Классические литературные издательства (Италия)
('Giulio Einaudi Editore', 'Итальянское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Италия')),
('Mondadori', 'Крупнейшее итальянское издательство', (SELECT id FROM countries WHERE name = 'Италия')),
('Garzanti', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Италия')),
('Bompiani', 'Издает художественную и гуманитарную литературу', (SELECT id FROM countries WHERE name = 'Италия')),

-- Классические литературные издательства (Испания)
('Editorial Planeta', 'Крупнейшее испанское издательство', (SELECT id FROM countries WHERE name = 'Испания')),
('Alfaguara', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Испания')),
('Editorial Anagrama', 'Известно изданием испанской и латиноамериканской литературы', (SELECT id FROM countries WHERE name = 'Испания')),

-- Классические литературные издательства (Япония)
('Kodansha', 'Крупнейшее японское издательство', (SELECT id FROM countries WHERE name = 'Япония')),
('Shueisha', 'Издает мангу и художественную литературу', (SELECT id FROM countries WHERE name = 'Япония')),
('Shogakukan', 'Издает мангу, детскую литературу', (SELECT id FROM countries WHERE name = 'Япония')),

-- Дополнительные российские издательства
('Эксмо-Пресс', 'Издает художественную литературу и детективы', (SELECT id FROM countries WHERE name = 'Россия')),
('АСТ-Пресс', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Книжный клуб Клуб семейного досуга', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Гелеос', 'Издает женские романы и любовную литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Центрполиграф', 'Издает детективы и историческую литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Вече', 'Издает историческую литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Амфора', 'Издает современную русскую литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Крылов', 'Издает литературу по бизнесу, психологии, IT', (SELECT id FROM countries WHERE name = 'Россия')),
('Наука', 'Академическое издательство, издает научную литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Молодая гвардия', 'Издает молодежную литературу, серию "Жизнь замечательных людей"', (SELECT id FROM countries WHERE name = 'Россия')),
('Детская литература', 'Издает классическую и современную детскую литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Правда', 'Издает классическую литературу', (SELECT id FROM countries WHERE name = 'Россия')),
('Художественная литература', 'Классическое издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Россия')),

-- Классические литературные издательства (Нидерланды)
('De Bezige Bij', 'Нидерландское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Нидерланды')),

-- Классические литературные издательства (Швеция)
('Norstedts Förlag', 'Шведское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Швеция')),
('Albert Bonniers Förlag', 'Издает шведскую художественную литературу', (SELECT id FROM countries WHERE name = 'Швеция')),

-- Классические литературные издательства (Норвегия)
('Gyldendal Norsk Forlag', 'Норвежское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Норвегия')),
('Aschehoug', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Норвегия')),

-- Классические литературные издательства (Дания)
('Gyldendal', 'Датское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Дания')),
('Lindhardt og Ringhof', 'Издает художественную литературу', (SELECT id FROM countries WHERE name = 'Дания')),

-- Классические литературные издательства (Австралия)
('Allen & Unwin', 'Австралийское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Австралия')),
('Text Publishing', 'Издает австралийскую художественную литературу', (SELECT id FROM countries WHERE name = 'Австралия')),

-- Классические литературные издательства (Канада)
('McClelland & Stewart', 'Канадское издательство художественной литературы', (SELECT id FROM countries WHERE name = 'Канада')),
('House of Anansi Press', 'Издает канадскую художественную литературу', (SELECT id FROM countries WHERE name = 'Канада'));


-- =====================================================
-- Описание: Заполнение справочника жанров
-- =====================================================

INSERT INTO genres (name) VALUES
-- Художественная литература (Fiction)
('Роман'),
('Повесть'),
('Рассказ'),
('Новелла'),
('Эпопея'),
('Сага'),
('Сказка'),
('Басня'),
('Притча'),
('Легенда'),
('Миф'),
('Поэма'),
('Поэзия'),
('Стихотворение'),
('Драматургия'),
('Пьеса'),
('Комедия'),
('Трагедия'),
('Трагикомедия'),
('Эссе'),

-- Жанры по содержанию (художественная)
('Детектив'),
('Триллер'),
('Мистика'),
('Ужасы'),
('Фантастика'),
('Научная фантастика'),
('Фэнтези'),
('Городское фэнтези'),
('Эпическое фэнтези'),
('Темное фэнтези'),
('Юмористическое фэнтези'),
('Боевое фэнтези'),
('Историческое фэнтези'),
('Магический реализм'),
('Альтернативная история'),
('Стимпанк'),
('Киберпанк'),
('Постапокалипсис'),
('Антиутопия'),
('Утопия'),
('Драма'),
('Мелодрама'),
('Любовный роман'),
('Исторический роман'),
('Приключения'),
('Вестерн'),
('Шпионский роман'),
('Криминальный роман'),
('Психологический роман'),
('Философский роман'),
('Автобиография'),
('Мемуары'),
('Биография'),
('Путевые заметки'),
('Документальная проза'),
('Публицистика'),

-- Детская литература
('Детская литература'),
('Сказки для детей'),
('Детские стихи'),
('Детские рассказы'),
('Детские повести'),
('Комиксы'),
('Манга'),
('Графический роман'),

-- Научно-популярная литература (Non-fiction)
('Научно-популярная литература'),
('Естественные науки'),
('Физика'),
('Химия'),
('Биология'),
('Астрономия'),
('География'),
('Геология'),
('Математика'),
('Информатика'),
('Компьютерная литература'),
('Программирование'),
('Алгоритмы и структуры данных'),
('Базы данных'),
('Сети и безопасность'),
('Искусственный интеллект'),
('Машинное обучение'),
('Веб-разработка'),
('Мобильная разработка'),
('DevOps и администрирование'),
('Операционные системы'),
('История науки и техники'),
('Психология'),
('Социология'),
('Философия'),
('Лингвистика'),
('Культурология'),
('Искусство и искусствоведение'),
('Архитектура'),

-- Бизнес и экономика
('Бизнес-литература'),
('Менеджмент'),
('Маркетинг'),
('Экономика'),
('Финансы'),
('Стартапы'),
('Личностный рост'),
('Саморазвитие'),
('Карьера и профориентация'),
('Инвестиции'),
('Право'),

-- История и политика
('Историческая литература'),
('Всемирная история'),
('История России'),
('История стран и народов'),
('Политика и политология'),
('Дипломатия'),

-- Религия и духовность
('Религиозная литература'),
('Духовная литература'),
('Богословие'),
('Философия религии'),
('Эзотерика'),
('Мистическая литература'),

-- Спорт и здоровье
('Спорт'),
('Фитнес и здоровье'),
('Здоровое питание'),
('Активный образ жизни'),
('Туризм'),
('Кулинария'),
('Хобби и увлечения'),

-- Образование и справочники
('Учебная литература'),
('Справочная литература'),
('Энциклопедия'),
('Словарь'),
('Учебник для вузов'),
('Методическое пособие'),

-- Искусство и культура
('Искусство'),
('Живопись'),
('Музыка'),
('Кино и театр'),
('Фотография'),
('Дизайн'),
('Культура'),

-- Популярные и массовые жанры
('Лайфстайл'),
('Дом и быт'),
('Садоводство'),
('Рукоделие'),
('Косметология'),
('Психология отношений'),
('Семейная психология'),

-- Фантастические поджанры (дополнительно)
('Космическая опера'),
('Твердая научная фантастика'),
('Мягкая научная фантастика'),
('Детская фантастика'),
('Фантастика ужасов'),
('Зомби-апокалипсис'),
('ЛитРПГ'),
('РеалРПГ'),

-- Детективные поджанры
('Классический детектив'),
('Полицейский детектив'),
('Психологический детектив'),
('Шпионский детектив'),
('Иронический детектив'),

-- Дополнительные жанры
('Афоризмы и цитаты'),
('Анекдоты и юмор'),
('Книги для досуга'),
('Кроссворды и головоломки');

-- =====================================================
-- Описание: Заполнение справочника групп литературы
-- =====================================================

INSERT INTO literature_groups (name) VALUES
-- Основные категории (самые общие)
('Художественная литература'),
('Документальная литература'),
('Научная литература'),
('Научно-популярная литература'),
('Учебная литература'),
('Справочная литература'),
('Детская литература'),
('Подростковая литература');

-- =====================================================
-- Описание: Заполнение справочника языков
-- =====================================================

-- =====================================================
-- Миграция: V7__init_languages.sql
-- Описание: Заполнение справочника языков
-- =====================================================

INSERT INTO languages (name) VALUES
-- Индоевропейские языки
('Английский'),
('Русский'),
('Немецкий'),
('Французский'),
('Испанский'),
('Итальянский'),
('Португальский'),
('Нидерландский'),
('Шведский'),
('Норвежский'),
('Датский'),
('Исландский'),
('Фарерский'),
('Латинский'),
('Греческий'),
('Древнегреческий'),
('Санскрит'),
('Хинди'),
('Урду'),
('Бенгальский'),
('Панджаби'),
('Маратхи'),
('Гуджарати'),
('Ория'),
('Синдхи'),
('Непальский'),
('Сингальский'),
('Курдский'),
('Персидский (фарси)'),
('Таджикский'),
('Пушту'),
('Дарри'),
('Осетинский'),
('Армянский'),
('Албанский'),

-- Славянские языки
('Украинский'),
('Белорусский'),
('Польский'),
('Чешский'),
('Словацкий'),
('Болгарский'),
('Сербский'),
('Хорватский'),
('Боснийский'),
('Черногорский'),
('Македонский'),
('Словенский'),
('Верхнелужицкий'),
('Нижнелужицкий'),
('Кашубский'),

-- Балтийские языки
('Литовский'),
('Латышский'),
('Латгальский'),

-- Кельтские языки
('Ирландский'),
('Шотландский гэльский'),
('Уэльский'),
('Бретонский'),
('Мэнский'),

-- Тюркские языки
('Турецкий'),
('Азербайджанский'),
('Узбекский'),
('Казахский'),
('Татарский'),
('Башкирский'),
('Киргизский'),
('Туркменский'),
('Уйгурский'),
('Якутский'),
('Чувашский'),
('Каракалпакский'),
('Кумыкский'),

-- Финно-угорские языки
('Финский'),
('Венгерский'),
('Эстонский'),
('Мордовский'),
('Удмуртский'),
('Марийский'),
('Коми'),
('Карельский'),
('Хантыйский'),
('Мансийский'),

-- Монгольские языки
('Монгольский'),
('Бурятский'),
('Калмыцкий'),

-- Кавказские языки
('Грузинский'),
('Чеченский'),
('Ингушский'),
('Аварский'),
('Лакский'),
('Даргинский'),
('Абхазский'),
('Адыгейский'),
('Кабардино-черкесский'),

-- Уральские языки
('Ненецкий'),

-- Семитские языки
('Арабский'),
('Иврит'),
('Амхарский'),
('Тигринья'),
('Мальтийский'),
('Сирийский'),
('Арамейский'),

-- Афразийские языки
('Берберский'),
('Сомалийский'),
('Оромо'),
('Хауса'),
('Свахили'),

-- Сино-тибетские языки
('Китайский'),
('Кантонский'),
('Мандарин'),
('Тибетский'),
('Бирманский'),
('Таи'),

-- Японо-рюкюские языки
('Японский'),
('Рюкюский'),

-- Корейский язык
('Корейский'),

-- Тай-кадайские языки
('Тайский'),
('Лаосский'),

-- Австронезийские языки
('Индонезийский'),
('Малайский'),
('Филиппинский (тагальский)'),
('Яванский'),
('Сунданский'),
('Мадурский'),
('Вьетнамский'),
('Кхмерский'),
('Малагасийский'),

-- Дравидийские языки
('Тамильский'),
('Телугу'),
('Малаялам'),
('Каннада'),

-- Нигеро-конголезские языки
('Йоруба'),
('Игбо'),
('Акан'),
('Зулу'),
('Коса'),
('Африкаанс'),
('Сото'),
('Тсвана'),

-- Папуасские языки
('Ток-писин'),

-- Австралийские языки
('Аборигенные языки Австралии'),

-- Искусственные языки
('Эсперанто'),
('Лингва-франка'),
('Идо'),
('Волапюк'),
('Клингонский'),
('Эльфийские языки'),

-- Языки СНГ и России (без дублей)
('Агульский'),
('Алтайский'),
('Еврейский'),
('Карачаево-балкарский'),
('Лезгинский'),
('Молдавский'),
('Ногайский'),
('Тувинский'),
('Хакасский'),

-- Дополнительные языки (без дублей)
('Ассирийский'),
('Афарский'),
('Бамбара'),
('Баскский'),
('Белуджский'),
('Гаитянский креольский'),
('Гренландский'),
('Гуарани'),
('Дзонг-кэ'),
('Зулусский'),
('Инуктитут'),
('Кечуа'),
('Люксембургский'),
('Майя'),
('Мальдивский'),
('Маори'),
('Науруанский'),
('Пали'),
('Практический китайский'),
('Румынский'),
('Себуано'),
('Таитянский'),
('Тонга'),
('Фризский'),
('Цыганский'),
('Чаморро'),
('Шона');